### PR TITLE
Aligned the docker and kubelet cgroupdriver

### PR DESCRIPTION
**Pull request by jshaofuturewei**
The current deployment script does not add edge clusters when all the hosts are created.

The script is to add additional edge clusters to an existing clusters

### CODE REVIEW

**Review by pdgetrf — APPROVED** [review]
LGTM

**Comment by pdgetrf** [comment]
is this ready for merge?

**Comment by jshaofuturewei** [comment]
> is this ready for merge?

Yes

**Comment by jshaofuturewei** [comment]
Yes

**Pull request merged**
