### PR TITLE
Instruction Guide for Edge Cluster Multi-Layer Setup and Configuration 

### PR DESCRIPTION
**Pull request by davidzhu22**
The purpose of this document is to how to setup and configuration Cloud core and Edge core , and describe the each step to create virtual machine, setup the port number, install kubernets, GoLang, and so on. Running Cloud core and Edge core and deployed mission and task to Edge node. Improve the Edge computing. This Cloud and Edge design is derived from cloud end to edge end for Edge System Functional Description and the Setup Requirements Specification. The intended user of this program is the edge computing user.

**Edge Cluster Multi-Layer Setup and Configuration**

1. This documentation  include following three files:
a. cluster_setup.md:  Edge Cluster Multi-Layer Setup and Configuration
b. edge_cluster_copy.md : File or Folder Copy Process Between Edge cluster
c. vm_setup.md :  Virtual Machine Setup and Configuration

2. This document is instruction Guide. (No bug fix)

### CODE REVIEW

**Comment by pdgetrf** [comment]
this PR has way too many (118) commits. Each PR should contain no more than 5 commits otherwise it will flood the commit history of the main branch. 

please squash these commits into a single commit.

**Review by pdgetrf — CHANGES_REQUESTED** [review]
please squash the commits.

**Comment by pdgetrf** [comment]
please re-open this PR to trigger the CI to run again.

**Comment by davidzhu22** [comment]
David Zhu close this PR with a cleared PR

**Pull request closed without merging**
